package Tampilan;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import Kelas.KategoriClass;
import Kelas.PenggunaClass;

public class KategoriFrame extends javax.swing.JFrame {

    /**
     * Creates new form KategoriFrame
     */
    public KategoriFrame() {
        initComponents();
        reset();
        loadTable();
    }

    void autoID() {

        KategoriClass catID = new KategoriClass();
        ResultSet rsVar = catID.autoID();
        try {

            if (rsVar.next()) {
                int id = rsVar.getInt("ID") + 1;
                txtIDCategory.setText(String.valueOf(id));
            } else {
                txtIDCategory.setText("1");
            }

        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }
    }

    void reset() {
        autoID();
        txtIDCategory.setEditable(false);
        txtNamaCategory.setText(null);
    }

// <editor-fold defaultstate="collapsed" desc="Kode Jaga-jaga">                              
//    void loadData(){
//        DefaultTableModel model = new DefaultTableModel();
//        categoryClass categoryData = new categoryClass();
//        
//        model.addColumn("ID Category");
//        model.addColumn("Nama Category");
//        
//        try {
//            ResultSet rsVar = categoryData.loadData();
//            
//            while (rsVar.next()) {
//                int id = rsVar.getInt("categoryId");
//                String nama = rsVar.getString("categoryNama");
//                
//                Object data[] = {id, nama};
//                model.addRow(data);
//            }
//        } catch (SQLException sQLException) {
//            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
//        }
//        tableCategory.setModel(model);
//    }// </editor-fold>
    void loadTable() {
        DefaultTableModel model = new DefaultTableModel();
        KategoriClass categoryData = new KategoriClass();

        model.addColumn("ID Category");
        model.addColumn("Nama Category");

        try {
            ResultSet rsVar = categoryData.loadData();

            while (rsVar.next()) {
                int id = rsVar.getInt("categoryId");
                String nama = rsVar.getString("categoryName");

                Object data[] = {id, nama};
                model.addRow(data);
            }
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }
        tableCategory.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDasar = new javax.swing.JPanel();
        btTambah = new javax.swing.JButton();
        btUbah = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        buttonKembali = new javax.swing.JButton();
        lbJudulKategori = new javax.swing.JLabel();
        pnInput = new javax.swing.JPanel();
        lbDKategori = new javax.swing.JLabel();
        lbNmKategori = new javax.swing.JLabel();
        txtIDCategory = new javax.swing.JTextField();
        txtNamaCategory = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCategory = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        mProduct = new javax.swing.JMenu();
        miCategory = new javax.swing.JMenu();
        miUser = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 560));

        pnDasar.setBackground(new java.awt.Color(0, 0, 255));
        pnDasar.setPreferredSize(new java.awt.Dimension(640, 560));

        btTambah.setBackground(new java.awt.Color(76, 175, 80));
        btTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btTambah.setForeground(new java.awt.Color(255, 255, 255));
        btTambah.setText("TAMBAH");
        btTambah.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });

        btUbah.setBackground(new java.awt.Color(33, 150, 243));
        btUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btUbah.setForeground(new java.awt.Color(255, 255, 255));
        btUbah.setText("UBAH");
        btUbah.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUbahActionPerformed(evt);
            }
        });

        btHapus.setBackground(new java.awt.Color(244, 67, 54));
        btHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btHapus.setForeground(new java.awt.Color(255, 255, 255));
        btHapus.setText("HAPUS");
        btHapus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        btReset.setBackground(new java.awt.Color(255, 152, 0));
        btReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btReset.setForeground(new java.awt.Color(255, 255, 255));
        btReset.setText("RESET");
        btReset.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        buttonKembali.setBackground(new java.awt.Color(102, 102, 102));
        buttonKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembali.setText("KEMBALI");
        buttonKembali.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        lbJudulKategori.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbJudulKategori.setForeground(new java.awt.Color(255, 255, 255));
        lbJudulKategori.setText("KATEGORI");

        pnInput.setBackground(new java.awt.Color(58, 58, 58));
        pnInput.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnInput.setPreferredSize(new java.awt.Dimension(349, 416));

        lbDKategori.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDKategori.setForeground(new java.awt.Color(255, 255, 255));
        lbDKategori.setText("ID KATEGORI");

        lbNmKategori.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNmKategori.setForeground(new java.awt.Color(255, 255, 255));
        lbNmKategori.setText("NAMA KATEGORI");

        txtIDCategory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        txtNamaCategory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        javax.swing.GroupLayout pnInputLayout = new javax.swing.GroupLayout(pnInput);
        pnInput.setLayout(pnInputLayout);
        pnInputLayout.setHorizontalGroup(
            pnInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInputLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIDCategory)
                    .addGroup(pnInputLayout.createSequentialGroup()
                        .addGroup(pnInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDKategori)
                            .addComponent(lbNmKategori))
                        .addGap(0, 214, Short.MAX_VALUE))
                    .addComponent(txtNamaCategory))
                .addContainerGap())
        );
        pnInputLayout.setVerticalGroup(
            pnInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInputLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbDKategori)
                .addGap(8, 8, 8)
                .addComponent(txtIDCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbNmKategori)
                .addGap(13, 13, 13)
                .addComponent(txtNamaCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        tableCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCategory);

        javax.swing.GroupLayout pnDasarLayout = new javax.swing.GroupLayout(pnDasar);
        pnDasar.setLayout(pnDasarLayout);
        pnDasarLayout.setHorizontalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnDasarLayout.createSequentialGroup()
                            .addComponent(pnInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnDasarLayout.createSequentialGroup()
                                    .addComponent(btTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDasarLayout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbJudulKategori))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDasarLayout.setVerticalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbJudulKategori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(960, 40));

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("File");

        miLogout.setText("LOG OUT");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(miLogout);

        jMenuBar1.add(jMenu1);

        mProduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mProduct.setText("Product");
        mProduct.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mProductMenuSelected(evt);
            }
        });
        jMenuBar1.add(mProduct);

        miCategory.setBackground(new java.awt.Color(255, 255, 255));
        miCategory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miCategory.setText("Category");
        miCategory.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                miCategoryMenuSelected(evt);
            }
        });
        jMenuBar1.add(miCategory);

        miUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miUser.setText("User");
        miUser.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                miUserMenuSelected(evt);
            }
        });
        jMenuBar1.add(miUser);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDasar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDasar, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // TODO add your handling code here:
        PenggunaClass userLogOut = new PenggunaClass();
        userLogOut.logoutApp();

        dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_miLogoutActionPerformed

    private void mProductMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mProductMenuSelected
        // TODO add your handling code here:
        dispose();
        new ProdukFrame().setVisible(true);
    }//GEN-LAST:event_mProductMenuSelected

    private void miCategoryMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_miCategoryMenuSelected
        // TODO add your handling code here:
        dispose();
        new KategoriFrame().setVisible(true);
    }//GEN-LAST:event_miCategoryMenuSelected

    private void miUserMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_miUserMenuSelected
        // TODO add your handling code here:
        dispose();
        new PenggunaFrame().setVisible(true);
    }//GEN-LAST:event_miUserMenuSelected

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        // TODO add your handling code here:
        KategoriClass categorySave = new KategoriClass();

        categorySave.setCategoryId(Integer.parseInt(txtIDCategory.getText()));
        categorySave.setCategoryName(txtNamaCategory.getText());

        categorySave.saveData();

        reset();

        loadTable();
    }//GEN-LAST:event_btTambahActionPerformed

    private void btUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUbahActionPerformed
        // TODO add your handling code here:
        KategoriClass categoryUbah = new KategoriClass();

        categoryUbah.setCategoryId(Integer.parseInt(txtIDCategory.getText()));
        categoryUbah.setCategoryName(txtNamaCategory.getText());

        categoryUbah.updateData();

        reset();

        loadTable();

    }//GEN-LAST:event_btUbahActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
        KategoriClass categoryHapus = new KategoriClass();

        categoryHapus.setCategoryId(Integer.parseInt(txtIDCategory.getText()));

        categoryHapus.deleteData();

        reset();

        loadTable();
    }//GEN-LAST:event_btHapusActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btResetActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
        new BerandaFrame().setVisible(true);
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void tableCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCategoryMouseClicked
        // TODO add your handling code here:
        int choiceRow = tableCategory.rowAtPoint(evt.getPoint());

        String id = tableCategory.getValueAt(choiceRow, 0).toString();
        String nama = tableCategory.getValueAt(choiceRow, 1).toString();

        txtIDCategory.setText(id);
        txtNamaCategory.setText(nama);
    }//GEN-LAST:event_tableCategoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KategoriFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KategoriFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KategoriFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KategoriFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KategoriFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btUbah;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDKategori;
    private javax.swing.JLabel lbJudulKategori;
    private javax.swing.JLabel lbNmKategori;
    private javax.swing.JMenu mProduct;
    private javax.swing.JMenu miCategory;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenu miUser;
    private javax.swing.JPanel pnDasar;
    private javax.swing.JPanel pnInput;
    private javax.swing.JTable tableCategory;
    private javax.swing.JTextField txtIDCategory;
    private javax.swing.JTextField txtNamaCategory;
    // End of variables declaration//GEN-END:variables
}
