package Tampilan;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import Kelas.SesiClass;
import Kelas.PenggunaClass;

import Kelas.PenggunaClass;
import Kelas.SesiClass;

public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnGambar = new javax.swing.JPanel();
        pnLogin = new javax.swing.JPanel();
        lbNmPengguna = new javax.swing.JLabel();
        lbKtSandi = new javax.swing.JLabel();
        txNmPengguna = new javax.swing.JTextField();
        txKtSandi = new javax.swing.JPasswordField();
        txNmDev = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnGambar.setBackground(new java.awt.Color(46, 46, 56));
        pnGambar.setPreferredSize(new java.awt.Dimension(640, 600));

        javax.swing.GroupLayout pnGambarLayout = new javax.swing.GroupLayout(pnGambar);
        pnGambar.setLayout(pnGambarLayout);
        pnGambarLayout.setHorizontalGroup(
            pnGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        pnGambarLayout.setVerticalGroup(
            pnGambarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pnLogin.setBackground(new java.awt.Color(153, 153, 153));
        pnLogin.setPreferredSize(new java.awt.Dimension(320, 600));

        lbNmPengguna.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNmPengguna.setForeground(new java.awt.Color(255, 255, 255));
        lbNmPengguna.setText("NAMA PENGGUNA");

        lbKtSandi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbKtSandi.setForeground(new java.awt.Color(255, 255, 255));
        lbKtSandi.setText("KATA SANDI");

        txNmPengguna.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txNmPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNmPenggunaActionPerformed(evt);
            }
        });

        txKtSandi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txKtSandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txKtSandiActionPerformed(evt);
            }
        });

        txNmDev.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        txNmDev.setForeground(new java.awt.Color(255, 255, 255));
        txNmDev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txNmDev.setText("Powered By Angga Sanjaya");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGIN");

        btLogin.setBackground(new java.awt.Color(0, 102, 0));
        btLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btLogin.setForeground(new java.awt.Color(255, 255, 255));
        btLogin.setText("LOGIN");
        btLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btLogin.setIconTextGap(10);
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLoginLayout = new javax.swing.GroupLayout(pnLogin);
        pnLogin.setLayout(pnLoginLayout);
        pnLoginLayout.setHorizontalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txKtSandi, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbNmPengguna)
                                .addComponent(lbKtSandi)
                                .addComponent(txNmPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnLoginLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txNmDev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnLoginLayout.setVerticalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNmPengguna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txNmPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbKtSandi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txKtSandi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(txNmDev)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnGambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnGambar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        // 1. Ambil input dari form
        String userName = txNmPengguna.getText();
        String password = new String(txKtSandi.getPassword());

        // 2. Cek kalau kosong
        if (userName.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Nama pengguna dan kata sandi tidak boleh kosong",
                    "Login Gagal",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // 3. Panggil class Pengguna untuk proses login
        Kelas.PenggunaClass pengguna = new Kelas.PenggunaClass();
        pengguna.setUserName(userName);
        pengguna.setUserPassword(password);
        pengguna.loginApp();   // fungsi ini yang ngecek ke database dan isi SesiClass

        // 4. Cek status dari SesiClass
        if ("Active".equalsIgnoreCase(Kelas.SesiClass.getStatus())) {
            // login berhasil, buka Beranda
            new Tampilan.BerandaFrame().setVisible(true);
            this.dispose(); // nutup form login
        } else {
            // login gagal / user tidak aktif
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Login gagal. Periksa nama pengguna atau kata sandi.",
                    "Login Gagal",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btLoginActionPerformed

    private void txNmPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNmPenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNmPenggunaActionPerformed

    private void txKtSandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txKtSandiActionPerformed
        // TODO add your handling code here:
        PenggunaClass userLog = new PenggunaClass();
        userLog.setUserPassword(txKtSandi.getText());
        userLog.loginApp();
    }//GEN-LAST:event_txKtSandiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbKtSandi;
    private javax.swing.JLabel lbNmPengguna;
    private javax.swing.JPanel pnGambar;
    private javax.swing.JPanel pnLogin;
    private javax.swing.JPasswordField txKtSandi;
    private javax.swing.JLabel txNmDev;
    private javax.swing.JTextField txNmPengguna;
    // End of variables declaration//GEN-END:variables
}
