package Tampilan;

import Kelas.KategoriClass;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Kelas.PenggunaClass;
import java.sql.*;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class PenggunaFrame extends javax.swing.JFrame {

    /**
     * Creates new form PenggunaFrame
     */
    public PenggunaFrame() {
        initComponents();
        reset();
        // loadData();
        loadTable();
    }

    void reset() {
        txNmPengguna.setText(null);
        txKtSandi.setText(null);
        txEmail.setText(null);
        txNmLengkap.setText(null);
        cbStatus.setSelectedIndex(0);
    }

// <editor-fold defaultstate="collapsed" desc="Kode Jaga-jaga">                                  
//    void loadData() {
//
//        DefaultTableModel model = new DefaultTableModel();
//        userClass userData = new userClass();
//
//        model.addColumn("Username");
//        model.addColumn("Email");
//        model.addColumn("Password");
//        model.addColumn("Full Name");
//        model.addColumn("Status");
//
//        try {
//            ResultSet rsVar = userData.loadData();
//
//            while (rsVar.next()) {
//                String username = rsVar.getString("userName");
//                String email = rsVar.getString("userEmail");
//                String password = rsVar.getString("userPassword");
//                String fullName = rsVar.getString("userFullName");
//                byte status = rsVar.getByte("userStatus");
//
//                Object data[] = {username, email, password, fullName, status};
//                model.addRow(data);
//            }
//
//        } catch (SQLException sQLException) {
//            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
//        }
//        tableUser.setModel(model);
//    }// </editor-fold>
    void loadTable() {

        DefaultTableModel model = new DefaultTableModel();
        PenggunaClass userData = new PenggunaClass();

        model.addColumn("Username");
        model.addColumn("Email");

        model.addColumn("Full Name");
        model.addColumn("Status");

        try {

            ResultSet rsVar = userData.loadData();

            while (rsVar.next()) {
                String status = (rsVar.getInt("userStatus") == 1) ? "Active" : "Non-Active";

                model.addRow(new Object[]{
                    rsVar.getString("userName"),
                    rsVar.getString("userEmail"),
                    rsVar.getString("userFullName"),
                    status
                });
            }
            tbPengguna.setModel(model);
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btTambah = new javax.swing.JButton();
        btUbah = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        buttonKembali = new javax.swing.JButton();
        lbJudulPengguna = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPengguna = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lbNmPengguna = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbKtSandi = new javax.swing.JLabel();
        lbNmLengkap = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        txNmPengguna = new javax.swing.JTextField();
        txEmail = new javax.swing.JTextField();
        txNmLengkap = new javax.swing.JTextField();
        txKtSandi = new javax.swing.JPasswordField();
        cbStatus = new javax.swing.JComboBox<>();
        cbxShowPassword = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        mProduct = new javax.swing.JMenu();
        miCategory = new javax.swing.JMenu();
        miUser = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 600));

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 560));

        btTambah.setBackground(new java.awt.Color(76, 175, 80));
        btTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btTambah.setForeground(new java.awt.Color(255, 255, 255));
        btTambah.setText("TAMBAH");
        btTambah.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });

        btUbah.setBackground(new java.awt.Color(33, 150, 243));
        btUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btUbah.setForeground(new java.awt.Color(255, 255, 255));
        btUbah.setText("UBAH");
        btUbah.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUbahActionPerformed(evt);
            }
        });

        btHapus.setBackground(new java.awt.Color(244, 67, 54));
        btHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btHapus.setForeground(new java.awt.Color(255, 255, 255));
        btHapus.setText("HAPUS");
        btHapus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        btReset.setBackground(new java.awt.Color(255, 152, 0));
        btReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btReset.setForeground(new java.awt.Color(255, 255, 255));
        btReset.setText("RESET");
        btReset.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        buttonKembali.setBackground(new java.awt.Color(102, 102, 102));
        buttonKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKembali.setForeground(new java.awt.Color(255, 255, 255));
        buttonKembali.setText("KEMBALI");
        buttonKembali.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });

        lbJudulPengguna.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbJudulPengguna.setForeground(new java.awt.Color(255, 255, 255));
        lbJudulPengguna.setText("PENGGUNA");
        lbJudulPengguna.setFocusable(false);

        tbPengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPenggunaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPengguna);

        jPanel2.setBackground(new java.awt.Color(58, 58, 58));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setPreferredSize(new java.awt.Dimension(349, 416));

        lbNmPengguna.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNmPengguna.setForeground(new java.awt.Color(255, 255, 255));
        lbNmPengguna.setText("NAMA PENGGUNA");

        lbEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(255, 255, 255));
        lbEmail.setText("EMAIL");

        lbKtSandi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbKtSandi.setForeground(new java.awt.Color(255, 255, 255));
        lbKtSandi.setText("KATA SANDI");

        lbNmLengkap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNmLengkap.setForeground(new java.awt.Color(255, 255, 255));
        lbNmLengkap.setText("NAMA LENGKAP");

        lbStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbStatus.setForeground(new java.awt.Color(255, 255, 255));
        lbStatus.setText("STATUS");

        txNmPengguna.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        txEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        txNmLengkap.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Tidak Aktif" }));

        cbxShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        cbxShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxShowPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txNmPengguna)
                    .addComponent(txEmail)
                    .addComponent(cbStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, 321, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbStatus)
                            .addComponent(lbNmLengkap)
                            .addComponent(lbNmPengguna)
                            .addComponent(lbEmail)
                            .addComponent(lbKtSandi))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txKtSandi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxShowPassword))
                    .addComponent(txNmLengkap))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbNmPengguna)
                .addGap(8, 8, 8)
                .addComponent(txNmPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lbEmail)
                .addGap(13, 13, 13)
                .addComponent(txEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxShowPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txKtSandi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(lbKtSandi)
                        .addGap(52, 52, 52)
                        .addComponent(lbNmLengkap)
                        .addGap(16, 16, 16)))
                .addComponent(txNmLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lbStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbJudulPengguna))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbJudulPengguna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)))
                .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(960, 40));

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("File");

        miLogout.setText("LOG OUT");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(miLogout);

        jMenuBar1.add(jMenu1);

        mProduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mProduct.setText("Product");
        mProduct.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mProductMenuSelected(evt);
            }
        });
        jMenuBar1.add(mProduct);

        miCategory.setBackground(new java.awt.Color(255, 255, 255));
        miCategory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miCategory.setText("Category");
        miCategory.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                miCategoryMenuSelected(evt);
            }
        });
        jMenuBar1.add(miCategory);

        miUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miUser.setText("User");
        miUser.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                miUserMenuSelected(evt);
            }
        });
        jMenuBar1.add(miUser);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // TODO add your handling code here:
        PenggunaClass userLogOut = new PenggunaClass();
        userLogOut.logoutApp();

        dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_miLogoutActionPerformed

    private void mProductMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mProductMenuSelected
        // TODO add your handling code here:
        dispose();
        new ProdukFrame().setVisible(true);
    }//GEN-LAST:event_mProductMenuSelected

    private void miCategoryMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_miCategoryMenuSelected
        // TODO add your handling code here:
        dispose();
        new KategoriFrame().setVisible(true);
    }//GEN-LAST:event_miCategoryMenuSelected

    private void miUserMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_miUserMenuSelected
        // TODO add your handling code here:
        dispose();
        new PenggunaFrame().setVisible(true);
    }//GEN-LAST:event_miUserMenuSelected

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        // TODO add your handling code here:
        if (txNmPengguna.getText().isBlank() || txEmail.getText().isBlank() || txKtSandi.getText().isBlank() || txNmLengkap.getText().isBlank() || (cbStatus.getSelectedItem() == null)) {
            JOptionPane.showMessageDialog(null, "Harap mengisi data secara keseluruhan");
            return;
        }

        PenggunaClass userTambah = new PenggunaClass();

        userTambah.setUserName(txNmPengguna.getText());
        userTambah.setUserEmail(txEmail.getText());
        userTambah.setUserPassword(txKtSandi.getText());
        userTambah.setUserFullName(txNmLengkap.getText());

        String statusText = cbStatus.getSelectedItem().toString();
        userTambah.setUserStatus(statusText.equalsIgnoreCase("Aktif") ? 1 : 0);

//        String status = cbStatus.getSelectedItem().toString();
//        byte statusByte;
//
//        if (status.equalsIgnoreCase("Active")) {
//            statusByte = 1;
//        } else {
//            statusByte = 0;
//        }
//
//        userTambah.setUserStatus(statusByte);
        userTambah.saveData();

        reset();
        loadTable();
    }//GEN-LAST:event_btTambahActionPerformed

    private void btUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUbahActionPerformed
        // TODO add your handling code here:
        if (txNmPengguna.getText().isBlank() || txEmail.getText().isBlank() || txNmLengkap.getText().isBlank() || (cbStatus.getSelectedItem() == null)) {
            JOptionPane.showMessageDialog(null, "Harap mengisi data secara keseluruhan");
            return;
        }

        PenggunaClass userUbah = new PenggunaClass();

        userUbah.setUserName(txNmPengguna.getText());
        userUbah.setUserEmail(txEmail.getText());
        userUbah.setUserPassword(txKtSandi.getText());
        userUbah.setUserFullName(txNmLengkap.getText());

        String statusText = cbStatus.getSelectedItem().toString();
        userUbah.setUserStatus(statusText.equalsIgnoreCase("Aktif") ? 1 : 0);

        userUbah.updateData();

        reset();
        loadTable();
    }//GEN-LAST:event_btUbahActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
        if (txNmPengguna.getText().isBlank() || txEmail.getText().isBlank() || txKtSandi.getText().isBlank() || txNmLengkap.getText().isBlank() || (cbStatus.getSelectedItem() == null)) {
            JOptionPane.showMessageDialog(null, "Harap memilih data yang ingin dihapus");
            return;
        }

        PenggunaClass userTambah = new PenggunaClass();

        userTambah.setUserName(txNmPengguna.getText());

        userTambah.deleteData();

        reset();
        loadTable();
    }//GEN-LAST:event_btHapusActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
        new BerandaFrame().setVisible(true);
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void tbPenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPenggunaMouseClicked
        // TODO add your handling code here:
        int choiceRow = tbPengguna.rowAtPoint(evt.getPoint());

        String username = tbPengguna.getValueAt(choiceRow, 0).toString();
        String email = tbPengguna.getValueAt(choiceRow, 1).toString();
        String fullName = tbPengguna.getValueAt(choiceRow, 2).toString();
        String status = tbPengguna.getValueAt(choiceRow, 3).toString();

        txNmPengguna.setText(username);
        txNmPengguna.setEditable(false);
        txEmail.setText(email);
        txNmLengkap.setText(fullName);
        cbStatus.setSelectedItem(status);
    }//GEN-LAST:event_tbPenggunaMouseClicked

    private void cbxShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxShowPasswordActionPerformed
        // TODO add your handling code here:
        if (cbxShowPassword.isSelected()) {
            txKtSandi.setEchoChar((char) 0);
        } else {
            txKtSandi.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_cbxShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenggunaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenggunaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenggunaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenggunaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenggunaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btUbah;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JCheckBox cbxShowPassword;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbJudulPengguna;
    private javax.swing.JLabel lbKtSandi;
    private javax.swing.JLabel lbNmLengkap;
    private javax.swing.JLabel lbNmPengguna;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JMenu mProduct;
    private javax.swing.JMenu miCategory;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenu miUser;
    private javax.swing.JTable tbPengguna;
    private javax.swing.JTextField txEmail;
    private javax.swing.JPasswordField txKtSandi;
    private javax.swing.JTextField txNmLengkap;
    private javax.swing.JTextField txNmPengguna;
    // End of variables declaration//GEN-END:variables
}
