package Tampilan;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import Kelas.KategoriClass;
import Kelas.PenggunaClass;
import Kelas.ProdukClass;

public class ProdukFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProdukFrame
     */
    public ProdukFrame() {
        initComponents();
        loadData();
        valueComboBox();
        reset();
    }

    void autoId() {

        try {
            ProdukClass proId = new ProdukClass();
            ResultSet rsVar = proId.autoId();

            if (rsVar.next()) {
                int id = rsVar.getInt("ID") + 1;
                txIDProduk.setText(String.valueOf(id));
            } else {
                txIDProduk.setText("1");
            }

        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }
    }

    void reset() {
        autoId();
        txIDProduk.setEditable(false);
        txNmProduk.setText(null);
        txDskpProduk.setText(null);
        txHrgProduk.setText(null);
        cbKtgrProduk.setSelectedIndex(0);
    }

    void loadData() {
        DefaultTableModel model = new DefaultTableModel();
        ProdukClass productData = new ProdukClass();

        model.addColumn("ID Produk");
        model.addColumn("Nama Produk");
        model.addColumn("Kategori Produk");
        model.addColumn("Deskripsi Produk");
        model.addColumn("Harga Produk");

        ResultSet rsVar = productData.showProduct();
        try {

            while (rsVar.next()) {
                int id = rsVar.getInt("productId");
                String name = rsVar.getString("productName");
                String category = rsVar.getString("categoryName");
                String description = rsVar.getString("productDescription");
                int price = rsVar.getInt("productPrice");

                Object[] data = {id, name, category, description, price};
                model.addRow(data);
            }

        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }
        tbProduk.setModel(model);
    }

    void valueComboBox() {

        try {
            KategoriClass value = new KategoriClass();
            ResultSet rsVar = value.dataComboBox();

            while (rsVar.next()) {
                String data = rsVar.getString("categoryName");
                cbKtgrProduk.addItem(data);
            }

        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDasar = new javax.swing.JPanel();
        btTambah = new javax.swing.JButton();
        btUbah = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        btKembali = new javax.swing.JButton();
        lbJudulProduk = new javax.swing.JLabel();
        pnInput = new javax.swing.JPanel();
        lbIDProduk = new javax.swing.JLabel();
        lbNmProduk = new javax.swing.JLabel();
        lbKtgrProduk = new javax.swing.JLabel();
        lbDskpProduk = new javax.swing.JLabel();
        lbHrgProduk = new javax.swing.JLabel();
        txIDProduk = new javax.swing.JTextField();
        txNmProduk = new javax.swing.JTextField();
        txDskpProduk = new javax.swing.JTextField();
        cbKtgrProduk = new javax.swing.JComboBox<>();
        txHrgProduk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduk = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        mProduct = new javax.swing.JMenu();
        miCategory = new javax.swing.JMenu();
        miUser = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnDasar.setBackground(new java.awt.Color(0, 0, 255));
        pnDasar.setPreferredSize(new java.awt.Dimension(640, 560));

        btTambah.setBackground(new java.awt.Color(76, 175, 80));
        btTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btTambah.setForeground(new java.awt.Color(255, 255, 255));
        btTambah.setText("TAMBAH");
        btTambah.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });

        btUbah.setBackground(new java.awt.Color(33, 150, 243));
        btUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btUbah.setForeground(new java.awt.Color(255, 255, 255));
        btUbah.setText("UBAH");
        btUbah.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUbahActionPerformed(evt);
            }
        });

        btHapus.setBackground(new java.awt.Color(244, 67, 54));
        btHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btHapus.setForeground(new java.awt.Color(255, 255, 255));
        btHapus.setText("HAPUS");
        btHapus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        btReset.setBackground(new java.awt.Color(255, 152, 0));
        btReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btReset.setForeground(new java.awt.Color(255, 255, 255));
        btReset.setText("RESET");
        btReset.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });

        btKembali.setBackground(new java.awt.Color(102, 102, 102));
        btKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btKembali.setForeground(new java.awt.Color(255, 255, 255));
        btKembali.setText("KEMBALI");
        btKembali.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKembaliActionPerformed(evt);
            }
        });

        lbJudulProduk.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbJudulProduk.setForeground(new java.awt.Color(255, 255, 255));
        lbJudulProduk.setText("PRODUK");
        lbJudulProduk.setFocusable(false);

        pnInput.setBackground(new java.awt.Color(58, 58, 58));
        pnInput.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbIDProduk.setForeground(new java.awt.Color(255, 255, 255));
        lbIDProduk.setText("ID PRODUK");

        lbNmProduk.setForeground(new java.awt.Color(255, 255, 255));
        lbNmProduk.setText("NAMA PRODUK");

        lbKtgrProduk.setForeground(new java.awt.Color(255, 255, 255));
        lbKtgrProduk.setText("KATEGORI PRODUK");

        lbDskpProduk.setForeground(new java.awt.Color(255, 255, 255));
        lbDskpProduk.setText("DESKRIPSI PRODUK");

        lbHrgProduk.setForeground(new java.awt.Color(255, 255, 255));
        lbHrgProduk.setText("HARGA PRODUK");

        txIDProduk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        txNmProduk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        txDskpProduk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        txHrgProduk.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        javax.swing.GroupLayout pnInputLayout = new javax.swing.GroupLayout(pnInput);
        pnInput.setLayout(pnInputLayout);
        pnInputLayout.setHorizontalGroup(
            pnInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInputLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbKtgrProduk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txDskpProduk)
                    .addComponent(txNmProduk)
                    .addComponent(lbHrgProduk)
                    .addComponent(lbDskpProduk)
                    .addComponent(lbIDProduk)
                    .addComponent(lbNmProduk)
                    .addComponent(lbKtgrProduk)
                    .addComponent(txIDProduk)
                    .addComponent(txHrgProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnInputLayout.setVerticalGroup(
            pnInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInputLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbIDProduk)
                .addGap(8, 8, 8)
                .addComponent(txIDProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNmProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txNmProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lbKtgrProduk)
                .addGap(3, 3, 3)
                .addComponent(cbKtgrProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbDskpProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txDskpProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(lbHrgProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txHrgProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        tbProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProduk);

        javax.swing.GroupLayout pnDasarLayout = new javax.swing.GroupLayout(pnDasar);
        pnDasar.setLayout(pnDasarLayout);
        pnDasarLayout.setHorizontalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDasarLayout.createSequentialGroup()
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbJudulProduk)
                            .addGroup(pnDasarLayout.createSequentialGroup()
                                .addComponent(pnInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnDasarLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                        .addComponent(btTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnDasarLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jScrollPane1)))))))
                .addGap(27, 27, 27))
        );
        pnDasarLayout.setVerticalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbJudulProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(960, 40));

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("File");

        miLogout.setText("LOG OUT");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(miLogout);

        jMenuBar1.add(jMenu1);

        mProduct.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mProduct.setText("Product");
        mProduct.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mProductMenuSelected(evt);
            }
        });
        jMenuBar1.add(mProduct);

        miCategory.setBackground(new java.awt.Color(255, 255, 255));
        miCategory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miCategory.setText("Category");
        miCategory.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                miCategoryMenuSelected(evt);
            }
        });
        jMenuBar1.add(miCategory);

        miUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        miUser.setText("User");
        miUser.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                miUserMenuSelected(evt);
            }
        });
        jMenuBar1.add(miUser);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDasar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // TODO add your handling code here:
        PenggunaClass userLogOut = new PenggunaClass();
        userLogOut.logoutApp();

        dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_miLogoutActionPerformed

    private void mProductMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mProductMenuSelected
        // TODO add your handling code here:
        dispose();
        new ProdukFrame().setVisible(true);
    }//GEN-LAST:event_mProductMenuSelected

    private void miCategoryMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_miCategoryMenuSelected
        // TODO add your handling code here:
        dispose();
        new KategoriFrame().setVisible(true);
    }//GEN-LAST:event_miCategoryMenuSelected

    private void miUserMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_miUserMenuSelected
        // TODO add your handling code here:
        dispose();
        new PenggunaFrame().setVisible(true);
    }//GEN-LAST:event_miUserMenuSelected

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        // TODO add your handling code here:
        ProdukClass productTambah = new ProdukClass();
        KategoriClass categoryTambah = new KategoriClass();

        try {
            productTambah.setProductId(Integer.parseInt(txIDProduk.getText()));
            productTambah.setProductName(txNmProduk.getText());
            productTambah.setProductDescription(txDskpProduk.getText());
            productTambah.setProductPrice(Integer.parseInt(txHrgProduk.getText()));

            categoryTambah.setCategoryName(cbKtgrProduk.getSelectedItem().toString());
            ResultSet rsVarCek = categoryTambah.konversi();

            if (rsVarCek.next()) {
                int id = rsVarCek.getInt("categoryId");
                productTambah.setProductCategory(id);
            }

            productTambah.saveData();

        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null, "Error : " + numberFormatException.getMessage());
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }

        reset();
        loadData();
    }//GEN-LAST:event_btTambahActionPerformed

    private void btUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUbahActionPerformed
        // TODO add your handling code here:
        ProdukClass productTambah = new ProdukClass();
        KategoriClass categoryTambah = new KategoriClass();

        try {
            productTambah.setProductId(Integer.parseInt(txIDProduk.getText()));
            productTambah.setProductName(txNmProduk.getText());
            productTambah.setProductDescription(txDskpProduk.getText());
            productTambah.setProductPrice(Integer.parseInt(txHrgProduk.getText()));

            categoryTambah.setCategoryName(cbKtgrProduk.getSelectedItem().toString());
            ResultSet rsVarCek = categoryTambah.konversi();

            if (rsVarCek.next()) {
                int id = rsVarCek.getInt("categoryId");
                productTambah.setProductCategory(id);
            }

            productTambah.updateData();

        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null, "Error : " + numberFormatException.getMessage());
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error : " + sQLException.getMessage());
        }

        reset();
        loadData();
    }//GEN-LAST:event_btUbahActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
        ProdukClass productHapus = new ProdukClass();

        productHapus.setProductId(Integer.parseInt(txIDProduk.getText()));

        productHapus.deleteData();

        reset();
        loadData();
    }//GEN-LAST:event_btHapusActionPerformed

    private void btKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
        new BerandaFrame().setVisible(true);
    }//GEN-LAST:event_btKembaliActionPerformed

    private void tbProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProdukMouseClicked
        // TODO add your handling code here:
        int choiceRow = tbProduk.rowAtPoint(evt.getPoint());

        String id = tbProduk.getValueAt(choiceRow, 0).toString();
        String nama = tbProduk.getValueAt(choiceRow, 1).toString();
        String category = tbProduk.getValueAt(choiceRow, 2).toString();
        String deskripsi = tbProduk.getValueAt(choiceRow, 3).toString();
        String harga = tbProduk.getValueAt(choiceRow, 4).toString();

        txIDProduk.setText(id);
        txNmProduk.setText(nama);
        cbKtgrProduk.setSelectedItem(category);
        txDskpProduk.setText(deskripsi);
        txHrgProduk.setText(harga);
    }//GEN-LAST:event_tbProdukMouseClicked

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdukFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdukFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btKembali;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btUbah;
    private javax.swing.JComboBox<String> cbKtgrProduk;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDskpProduk;
    private javax.swing.JLabel lbHrgProduk;
    private javax.swing.JLabel lbIDProduk;
    private javax.swing.JLabel lbJudulProduk;
    private javax.swing.JLabel lbKtgrProduk;
    private javax.swing.JLabel lbNmProduk;
    private javax.swing.JMenu mProduct;
    private javax.swing.JMenu miCategory;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenu miUser;
    private javax.swing.JPanel pnDasar;
    private javax.swing.JPanel pnInput;
    private javax.swing.JTable tbProduk;
    private javax.swing.JTextField txDskpProduk;
    private javax.swing.JTextField txHrgProduk;
    private javax.swing.JTextField txIDProduk;
    private javax.swing.JTextField txNmProduk;
    // End of variables declaration//GEN-END:variables
}
